version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: finance_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:password@database/finance_tracker
      SECRET_KEY: your_secret_key
    depends_on:
      - database
    restart: always

  database:
    build:
      context: ./database
    container_name: postgres_transactions
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/data:/data
    restart: always

volumes:
  postgres_data:
