version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: finance_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:password@database/finance_tracker
      SECRET_KEY: your_secret_key
    depends_on:
      - database
    restart: always
    networks:
      - finance_network

  database:
    build:
      context: ./database
    container_name: postgres_transactions
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/data:/data
    restart: always
    networks:
      - finance_network

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    restart: always
    networks:
      - finance_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  # Expose NGINX on port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - finance_network

volumes:
  postgres_data:

networks:
  finance_network:
    driver: bridge
