version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: finance_backend
    environment:
      DATABASE_URL: postgresql://admin:password@database/finance_tracker
      SECRET_KEY: your_secret_key
    depends_on:
      - database
