version: "3.8"

services:
  database:
    image: postgres:17
    container_name: postgres_transactions
    ports:
      - "5432:5432" # Map PostgreSQL to host port 5432
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
      - ./init:/docker-entrypoint-initdb.d     # Initialization scripts
      - ./data:/data                          # Data for initialization
    restart: always

volumes:
  postgres_data:
