$ANSIBLE_VAULT;1.1;AES256
36646538643136646636376531306538366465613038646131396231633564653138646565313261
3633383839323266373735636337646233363463656239360a383436396361633636343865313932
37376535633037333333653764396337383665323961356563353561666663383435643238326466
3139376532383438370a376265663138353934653030633130313835363237626463316566373833
65323731316637653830373535306433353534663830373432393733633731333232363335356461
6361373661323036656334663466626561363332633437396234
